### ISSUE TITLE
API seems to be broken

### ISSUE THREAD

**Issue by maxkuhlmay** [vincep5/MMM-MyStandings#12]
My module keeps loading but without any success. 
Ive tried to debug and found, that the given URL shows HTTP Error 404.

My configuration:

```
 {
module: "MMM-MyStandings",
position: "bottom_right",
config: {
updateInterval: 60 * 60 * 24 * 1000, // once per day
rotateInterval: 1 * 60 * 1000, // once per minute
sports: [ {
league: "GER_BUNDESLIGA"
} ]
},
nameStyle: "short",
showLogos: true,
useLocalLogos: false,
fadeSpeed: 2000
},
```

This URL should point to http://site.web.api.espn.com/apis/v2/sports/soccer/ger.1 but it doesn’t work

**Comment by alexsmith1665** [comment]
Hi, I'm also getting a 404 error for that webpage. I see you've closed this issue - what was your solution if you don't mind sharing?
