### ISSUE TITLE
Division Rotation 

### ISSUE THREAD

**Issue by bam7** [vincep5/MMM-MyStandings#2]
I'm seeing behavior that the rotation goes all the way through the divisions, but stops at the last one and doesn't start over again.  (ex, MLB standings go thru all divisions, but stop rotating after NL WEST)

This happens when I use the long notation with all the divisions defined, or the short notation with just { league: "MLB" } defined.

There are no errors and the data is correct, but it just doesn't re-start it's rotation after cycling thru them once.

Thoughts?

**Comment by vincep5** [comment]
I have a bug, thanks for letting me know. I will check in the fix and you can git pull the changes.

**Comment by bam7** [comment]
The update appears to have worked.  The rotation is working.
Thanks
