### ISSUE TITLE
NCAA Rankings

### ISSUE THREAD

**Issue by tdworm** [vincep5/MMM-MyStandings#5]
Any chance to add NCAA rankings (football and bball) as options?

**Comment by vincep5** [comment]
I have recently did add NCAA football by division. I can do basketball next, but no timeline. I wanted to originally do it by top 25, but that is a different API call

**Comment by tdworm** [comment]
Thanks. I did find the ESPN api for the rankings but quickly realized I was in over my head trying to fork a version myself. It is a great module as-is; just wanted to ask about adding a rankings filter. Thanks again

**Comment by vincep5** [comment]
I've just added NCAAM to the supported sports.  Have a look at the latest code and pull it down and configure your conference!  The ESPN feed for just top 25 in NCAA Football and Basketball is different than the standings feed, so as of now, I don't expect to implement that data.
