### ISSUE TITLE
Stuck on loading...

### ISSUE THREAD

**Issue by sigel** [vincep5/MMM-MyStandings#6]
This still work, not getting any NFL data.

**Comment by vincep5** [comment]
Can you provide a snippet of code from your config of this module?
mine looks like this to show all NFL standings:
`        {
            module: "MMM-MyStandings",
            position: "top_left",
            config: {
                sports: [
                    { league: "NFL" },
                ]
            }
        },`
You may need to reboot the MagicMirror after saving changes.

**Comment by jloops412** [comment]
I've got the same issue. I've tried it numerous ways, including the way you've added here in your last comment. All still result in the module (and other modules) getting stuck in loading.

**Comment by vincep5** [comment]
Maybe check your Developer toolbar on your Magic Mirror for any other errors or the log for errors.
