### ISSUE TITLE
English Premier Leauge

### ISSUE THREAD

**Issue by bennykoo** [vincep5/MMM-MyStandings#7]
Hi,

I have started using your module and it is very nice.
I have two questions:

1. For some reason it doesnt work on ENGLISH PREMIER LEAGUE, do you have s solution for that.
2. haw can I use local symbols for Israeli clubs?

**Comment by vincep5** [comment]
can you post your section of the config for this module?
Mine is like this
`        {
            module: "MMM-MyStandings",
            position: "top_left",
            config: {
                showByDivision: false,
                sports: [
                    { league: "ITA_SERIE_A" },
                    { league: "ENG_PREMIERE_LEAGUE" },
                    { league: "ESP_LALIGA" },
                    { league: "GER_BUNDESLIGA" },
                ]
            }
        },`

**Comment by bennykoo** [comment]
yes, of course, it's like this:

{
		module: "MMM-MyStandings",
		position: "bottom_right",
		config: {
			updateInterval: 60 * 60 * 1000,			
			rotateInterval: 1 * 20 * 1000,
			 sports: [
			{ league: "ENG_PREMIER_LEAGUE" },
			{ league: "ISR_PREMIER_LEAGUE" },		
		]
			}
  		},

do you think I made it wrong?
I c that also on myscore modul there is the same problem - english premier league isn't shown, maybe ESPN have changed the league code?

**Comment by vincep5** [comment]
that looks correct to me.  No, the names have not changed.  I am able to see the Premier League standings and the scores too via MMM-MyScoreboard.  So its all working.  Maybe check your Developer toolbar on your Magic Mirror for any other errors or the log for errors.

**Comment by bennykoo** [comment]
How should I do that?

**Comment by vincep5** [comment]
Try searching for forums for debugging tips: https://forum.magicmirror.builders/
CTL+SHIFT+i brings up the dev toolbar

**Comment by bennykoo** [comment]
Sorry... not such talented programer, do you know some one who can log in to my computer from distance and try to fix it for me?
