### ISSUE TITLE
NHL divisions renamed for 2021 season.

### ISSUE THREAD

**Issue by thedfordfox** [vincep5/MMM-MyStandings#9]
Central is the only division that didn't get changed so it's the only one that still shows up.

**Comment by vincep5** [comment]
As a workaround, in the section of your config you can change the NHL to be
`{ league: "NHL", groups: ["Central Division", "East Division", "West Division", "North Division"] },`

**Comment by bam7** [comment]
I can confirm that the workaround works

**Comment by vincep5** [comment]
Great, no code change needed.  Hopefully the next season they will resume the normal schedule and divisions :)
